spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${test.db.url}
    username: ${test.db.username}
    password: ${test.db.password}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        create_empty_composites:
            enabled: true
#logging.level:
#  org.hibernate.SQL: debug

app-config:
  jwt :
    jwt-key: ${test.jwt.jwt_key}
    valid-time : ${test.jwt.valid_time}
  elastic:
    server-url: ${test.elastic.server_url}
    api-key: ${test.elastic.api_key}
    finger-print: ${test.elastic.finger_print}