spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${dev.db.url}
    username: ${dev.db.username}
    password: ${dev.db.password}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        create_empty_composites:
            enabled: true

app-config:
  jwt :
    jwt-key: ${dev.jwt.jwt_key}
    valid-time : ${dev.jwt.valid_time}
  elastic:
    server-url: ${dev.elastic.server_url}
    api-key : ${dev.elastic.api_key}
    finger-print : ${dev.elastic.finger_print}


logging:
  level:
    swm.s3.coclimb: debug
    sql: debug
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
    name: ./logs/coclimb.log
  logback:
    rollingpolicy:
      max-file-size: 500KB # 로그 파일의 최대 크기이며, 크기가 넘어가면 새로운 로그파일 작성
      max-history: 30 #로그 파일 최대 보관 일자
      file-name-pattern: ./logs/coclimb.%d{yyyy-MM-dd}.%i.log
      total-size-cap: 1000MB